export async function GET(request) {
  const products = [
    {
      id: 1,
      name: "Классическая шаверма",
      description: "Состав: Курица , свежий огурец, помидоры, морковь по-корейски, капуста салатная или капуста квашеная, красный лук, наш фирменный соус. 440гр.",
      price: 360,
      image: "/images/shawarma.jpg",
      category: "shawerma",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
    {
      id: 2,
      name: "Двойная шаверма",
      description: "Состав: Курица , свежий огурец, помидоры, морковь по-корейски, капуста салатная или капуста квашеная, красный лук, наш фирменный соус. 440гр.",
      price: 360,
      image: "/images/shawarma.jpg",
      category: "shawerma",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
    {
      id: 3,
      name: "Сырная шаверма",
      description: "Состав: Курица , свежий огурец, помидоры, морковь по-корейски, капуста салатная или капуста квашеная, красный лук, наш фирменный соус. 440гр.",
      price: 360,
      image: "/images/shawarma.jpg",
      category: "shawerma",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
    {
      id: 4,
      name: "Итальянская шаверма",
      description: "Состав: Курица , свежий огурец, помидоры, морковь по-корейски, капуста салатная или капуста квашеная, красный лук, наш фирменный соус. 440гр.",
      price: 360,
      image: "/images/shawarma.jpg",
      category: "new-items",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
    {
      id: 5,
      name: "Греческая шаверма",
      description: "Состав: Курица , свежий огурец, помидоры, морковь по-корейски, капуста салатная или капуста квашеная, красный лук, наш фирменный соус. 440гр.",
      price: 360,
      image: "/images/shawarma.jpg",
      category: "new-items",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
    {
      id: 6,
      name: "Картофель фри",
      description: "Прекрасный жаренный картофель. 150гр.",
      price: 100,
      image: "/images/fries.jpg",
      category: "snacks",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
    {
      id: 6,
      name: "Кофе Американо",
      description: "Горячий кофе для ценителей чистого вкуса. 0.4л",
      price: 139,
      image: "/images/coffee-americano.jpg",
      category: "hot-drinks",
      inStock: true,
      createdAt: "2024-12-01T10:00:00Z",
    },
  ];

  return new Response(JSON.stringify(products), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}